linters:
  Comment:
    enabled: true
    style: silent

  DeclarationOrder:
    enabled: false

  HexLength:
    enabled: false

  HexNotation:
    enabled: true
    style: uppercase

  Indentation:
    enabled: false
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: camel_case

  NestingDepth:
    enabled: false
    max_depth: 3
    ignore_parent_selectors: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  PropertySortOrder:
    enabled: true
    order:
        - z-index
        - visibility
        - opacity
        - display
        - position
        - top
        - right
        - bottom
        - left
        - float
        - clear
        - overflow

        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height

        - flex-direction
        - align-items

        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - box-shadow
        -
        - font
        - font-family
        - font-size
        - font-weight
        - font-smoothing
        - font-style
        -
        - transform
        - transition
        -
        - animation
        - animation-name
        - animation-duration
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        - animation-fill-mode
        - animation-play-state

    ignore_unspecified: true
    separate_groups: false

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: false

  SingleLinePerProperty:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space_or_newline

  SpaceBeforeBrace:
    enabled: false
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: false

  TrailingWhitespace:
    enabled: true

  ZeroUnit:
    enabled: true
